CREATE TABLE evenements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  du timestamp,
  au timestamp,
  nom varchar(255)
);

INSERT INTO evenements (
  du,
  au,
  nom
) VALUES (
  CURRENT_TIMESTAMP - 1 HOUR,
  CURRENT_TIMESTAMP + 1 HOUR,
  'Bonjour le monde!'
);
